# Generated by Django 5.0.7 on 2024-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=100)),
                ('case_description', models.TextField()),
                ('case_status', models.CharField(max_length=50)),
                ('case_priority', models.CharField(max_length=50)),
                ('case_assignee', models.CharField(max_length=50)),
                ('case_created', models.DateTimeField(auto_now_add=True)),
                ('case_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
